PATCH_FILE: './results/military_patch-15.png'
DATA_ROOT: './data/military_data/JPEGImages'
IMG_SAVE_PATH: './data/military_data/STEP15/imgs'
DETECT_SAVE_PATH: './data/military_data/DetectedLabels'
ATTACKED_DETECT_SAVE_PATH: './data/military_data/STEP15/labels'

DETECTOR:
  NAME: ["Military_YOLOX", "Military_FasterRCNN"]
  INPUT_SIZE: [416, 416]
  BATCH_SIZE: 1 # be fixed into 1 for evaluation
  CLASS_NAME_FILE: './configs/namefiles/military.names'

ATTACKER:
  ATTACK_CLASS: 1
  PATCH_ATTACK:
    SCALE: 0.2

EVALUATOR:
  IOU_THRESH: 0.5
  CONF_THRESH: 0.5