DATA:
  CLASS_NAME_FILE: 'configs/namefiles/coco.names'
  AUGMENT: '3'

  TRAIN:
    IMG_DIR: 'data/INRIAPerson/Train/pos'
    LAB_DIR: 'data/INRIAPerson/Train/labels/yolo-labels'

  TEST:
    IMG_DIR: 'data/INRIAPerson/Test/pos'
    LAB_DIR: 'data/INRIAPerson/Test/labels'

DETECTOR:
  NAME: ["faster_rcnn"] # YOLOV3, YOLOV4, YOLOV5
  INPUT_SIZE: [416, 416] # height, width
  BATCH_SIZE: 8

  CONF_THRESH: 0.5
  IOU_THRESH: 0.45
  ATTACK_CONF_THRESH: 0.3

  PERTURB:
    GATE: null

ATTACKER:
  METHOD: "pgd"
  EPSILON: 255 # 0-255
  MAX_EPOCH: 500
  ITER_STEP: 1
  STEP_SIZE: 0.01
  TARGET_CLASS:
  ATTACK_CLASS: '0' # -1 attack all classes, or you can select the class id
  LOSS_FUNC: "descend-mse" # [null, descend-mse, ascend-mse]
  tv_eta: 2.5
  obj_eta: 1
  START_LEARNING_RATE: 0.03

  PATCH_ATTACK:
    WIDTH: 300
    HEIGHT: 300
    SCALE: 0.2
    INIT: "gray" # ['random', 'gray']
    ASPECT_RATIO: 1