DATA:
  IMG_DIR: './data/coco/train/train2017'
  LAB_DIR:
  CLASS_NAME_FILE: './configs/namefiles/coco.names'

DETECTOR:
  # "Military_YOLOX", , "YOLOV5"
  NAME: ["YOLOV3", "YOLOV4"] # YOLOV3, YOLOV4, YOLOV5
  INPUT_SIZE: [416, 416] # height, width
  BATCH_SIZE: 2
  CONF_THRESH: 0.5
  IOU_THRESH: 0.45

ATTACKER:
  METHOD: "pgd"
  EPSILON: 255 # 0-255
  MAX_ITERS: 2000
  ITER_STEP:
  STEP_SIZE: 0.005
  TARGET_CLASS: 0
  ATTACK_CLASS: '-1' # -1 attack all classes, or you can select the class id

  PATCH_ATTACK:
    WIDTH: 128
    HEIGHT: 128
    SCALE: 0.1
    ASPECT_RATIO: -1