DATA:
  CLASS_NAME_FILE: 'configs/namefiles/coco.names'
  AUGMENT: 0
  TRAIN:
    IMG_DIR: 'data/coco/train/train2017'

  TEST:
    IMG_DIR: 'data/coco/val/val2017'
    LAB_DIR: 'data/coco/val/val2017_labels'

DETECTOR:
  # "Military_YOLOX", , "YOLOV5"
  NAME: ["YOLOV3"] # YOLOV3, YOLOV4, YOLOV5
  BATCH_SIZE: 8

  INPUT_SIZE: [416, 416] # the original image size: height, width
  CONF_THRESH: 0.5
  IOU_THRESH: 0.45

  GRAD_PERTURB: 0

ATTACKER:
  METHOD: "pgd"
  EPSILON: 255 # 0-255
  MAX_ITERS: 100
  SERIAL_ITER_STEP: 5
  PARALLEL_ITER_STEP: 10
  STEP_SIZE: 0.005
  TARGET_CLASS: 0 # targeted attack
  ATTACK_CLASS: '-1' # String: '-1' attack all classes; appoint a class 'x'; 'a:b' class list a to b - 1

  PATCH_ATTACK:
    WIDTH: 128
    HEIGHT: 128
    SCALE: 0.2
    AREA_RATIO: 1 # 1: True; 0: False