DETECTOR:
  # "Military_YOLOX", , "YOLOV5"
  NAME: ["YOLOV3", "YOLOV4"] # YOLOV3, YOLOV4, YOLOV5
  INPUT_SIZE: [416, 416] # height, width
  BATCH_SIZE: 2
  IMG_DIR: './data/coco/train/train2017'
  LAB_DIR:
  CLASS_NAME_FILE: './configs/namefiles/coco.names'

ATTACKER:
  METHOD: "pgd"
  EPSILON: 255 # 0-255
  MAX_ITERS: 2000
  SERIAL_ITER_STEP: 5
  PARALLEL_ITER_STEP: 10
  STEP_SIZE: 0.005
  TARGET_CLASS: 0
  ATTACK_CLASS: '0:40' # -1 attack all classes, or you can select the class id

  PATCH_ATTACK:
    WIDTH: 100
    HEIGHT: 100
    SCALE: 0.1
    FIX_RATIO: 0 # 1: True; 0: False