DETECTOR:
  # "Military_YOLOX", , "YOLOV5"
  NAME: ["YOLOV3"] # YOLOV3, YOLOV4, YOLOV5
  INPUT_SIZE: [416, 416] # height, width
  BATCH_SIZE: 2
  IMG_DIR: './data/INRIAPerson/Train/pos'
  LAB_DIR: './data/INRIAPerson/Train/pos/yolo-labels'
  CLASS_NAME_FILE: './configs/namefiles/coco.names'

ATTACKER:
  METHOD: "pgd"
  EPSILON: 255 # 0-255
  MAX_ITERS: 100
  SERIAL_ITER_STEP: 2
  PARALLEL_ITER_STEP: 15
  STEP_SIZE: 0.01
  TARGET_CLASS: 0
  ATTACK_CLASS: 0 # -1 attack all classes, or you can select the class id

  PATCH_ATTACK:
    SCALE: 0.1