PROJECT_DIR: '/home/chenziyan/work/BaseDetectionAttack'

DETECTOR:
  NAME: ["Faster_rcnn"] # YOLOV3, YOLOV4, YOLOV5
  BATCH_SIZE: 1
  IMG_DIR: 'data/coco/train/train2017'
  LAB_DIR:
  CLASS_NAME_FILE: 'configs/namefiles/coco-91.names'

  INPUT_SIZE: [416, 416] # the original image size: height, width
  CONF_THRESH: 0.3
  IOU_THRESH: 0.45

ATTACKER:
  METHOD: "pgd"
  EPSILON: 255 # 0-255
  MAX_ITERS: 2000
  SERIAL_ITER_STEP: 5
  PARALLEL_ITER_STEP: 15
  STEP_SIZE: 0.005
  TARGET_CLASS: 0
  ATTACK_CLASS: '0' # -1 attack all classes, or you can select the class id

  PATCH_ATTACK:
    WIDTH: 128
    HEIGHT: 128
    SCALE: 0.2
    AREA_RATIO: 1 # 1: True; 0: False