DATA:
  CLASS_NAME_FILE: 'configs/namefiles/coco.names' # a relative path
  AUGMENT: '13' # '1' contained: augment image when loading; '2' contained: augment the adv image in the second detection inference; '3' contained: augment adv patch

  TRAIN:
    IMG_DIR: 'data/INRIAPerson/Train/pos'
    LAB_DIR: 'data/INRIAPerson/Train/labels'

  TEST:
    IMG_DIR: 'data/INRIAPerson/Test/pos'
    LAB_DIR: 'data/INRIAPerson/Test/labels'

DETECTOR:
  NAME: ["Faster_RCNN"]   # [YOLOV3, YOLOV3-TINY, YOLOV4, YOLOV4-TINY, YOLOV5, FASTER_RCNN, SSD] 不区分大小写
  INPUT_SIZE: [416, 416]  # height, width
  BATCH_SIZE: 8           # batch size when training. BATCH_SIZE = const 1 when evaluating

  CONF_THRESH: 0.5        # confidence thresh in NMS
  IOU_THRESH: 0.45        # iou thresh in NMS

  PERTURB:
    GATE: null

ATTACKER:
  METHOD: "pgd" # attack algorithm: ['bim', 'pgd', 'mim']
  EPSILON: 255 # 0-255
  MAX_ITERS: 1000 # N Epoches
  ITER_STEP: 5 # Attack steps in every mini-batch
  STEP_SIZE: 0.005 # update rate. e.g. FGSM: step size * grad sign
  TARGET_CLASS: 0 # targeted attack
  ATTACK_CLASS: '0' # -1 attack all classes, or you can select the class id (corresponds to the namefile)

  LOSS_FUNC: "obj-tv" # [null, 'descend-mse', 'ascend-mse', 'obj', 'obj-tv]
  tv_eta: 2.5
  obj_eta: 1
  START_LEARNING_RATE: 0.03

  PATCH_ATTACK:
    WIDTH: 128 # Patch width
    HEIGHT: 128 # Patch height
    SCALE: 0.2 # patch scale when attaching patch on bbox
    INIT: "gray" # ['random', 'gray']
    AREA_RATIO: 1 # 1: square