DETECTOR:
  # "Military_YOLOX",
  NAME: ["Military_YOLOX", "Military_FasterRCNN"] # YOLOV3, YOLOV4, YOLOV5, Military_YOLOX, Military_FasterRCNN
  INPUT_SIZE: [416, 416] # height, width
  BATCH_SIZE: 2
  CLASS_NAME_FILE: './configs/namefiles/military.names'

ATTACKER:
  METHOD: "pgd"
  EPSILON: 255 # 0-255
  MAX_ITERS: 2000
  SERIAL_ITER_STEP: 5
  PARALLEL_ITER_STEP:
  STEP_SIZE: 0.01
  TARGET_CLASS: 0
  ATTACK_CLASS: 1 # -1 attack all classes, or you can select the class id

  PATCH_ATTACK:
    SCALE: 0.2